#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Swaha_for_Android.Resource", IsApplication=true)]

namespace Swaha_for_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int download = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ICONLOGO = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int PlayButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int TransparentPlay = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int Description = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int GoToPictureSelect = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int PreviewVid = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int PreviewVid1 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int PreviewVid2 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int PreviewVid3 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int PreviewVid4 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int PreviewVid5 = 2131165196;
			
			// aapt resource value: 0x7f070022
			public const int SelectPicturesGrid = 2131165218;
			
			// aapt resource value: 0x7f07001c
			public const int StoryPicture = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int Title = 2131165202;
			
			// aapt resource value: 0x7f070023
			public const int camRoll = 2131165219;
			
			// aapt resource value: 0x7f07001d
			public const int delete = 2131165213;
			
			// aapt resource value: 0x7f070000
			public const int gridImage = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int myButton = 2131165198;
			
			// aapt resource value: 0x7f07001a
			public const int photoTray = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int phototrayholder = 2131165211;
			
			// aapt resource value: 0x7f070015
			public const int previewButton = 2131165205;
			
			// aapt resource value: 0x7f070005
			public const int previewButton1 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int previewButton2 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int previewButton3 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int previewButton4 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int previewButton5 = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int scrollView1 = 2131165187;
			
			// aapt resource value: 0x7f07001e
			public const int start = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int stop = 2131165215;
			
			// aapt resource value: 0x7f070002
			public const int textViewMain = 2131165186;
			
			// aapt resource value: 0x7f070011
			public const int textViewPreview = 2131165201;
			
			// aapt resource value: 0x7f070019
			public const int textViewRecord = 2131165209;
			
			// aapt resource value: 0x7f070021
			public const int textViewSelect = 2131165217;
			
			// aapt resource value: 0x7f070017
			public const int toEmail = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int toPhone = 2131165206;
			
			// aapt resource value: 0x7f070024
			public const int toRecord = 2131165220;
			
			// aapt resource value: 0x7f070001
			public const int toolbarMain = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int toolbarPreview = 2131165200;
			
			// aapt resource value: 0x7f070018
			public const int toolbarRecord = 2131165208;
			
			// aapt resource value: 0x7f070020
			public const int toolbarSelect = 2131165216;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GridTile = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OpeningPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Preview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RecordScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SelectPictures = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int openCamera = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
